### ISSUE TITLE
To-do after email PR merged

### ISSUE THREAD

**Issue by indocomsoft** [commit-tech/takoyaki#37]
Some things on the email PR are running on a few assumptions, so make sure to check this after merging:
- [ ] Change email "from" field to the legit one, including in `app/mailer`'s `default from:` and `spec/mailer`'s  `DEFAULT_FROM`
- [ ] implement `duties#dropped` (or equivalent) for grab list, then uncomment the url's in `app/views/generic_mailer` and `spec/mailers` (watch for #41)
- [x] `ProblemReport` model has the `venue` column changed into `place` with `belongs_to :place`
- [x] uncomment `#problem_report` test in `spec/mailer` after problem-report branch is merged (watch for #36)
- [x] uncomment `@problem` in `app/views/generic_mailer/problem_report.*` when problem-report is merged. (watch for #36)

**Comment by donjar** [comment]
(refer to #34)
